name: DEV-CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCR_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: ./gradlew build --stacktrace
        
      - name: Install
        run: ./gradlew install

      - name: List files
        run: ls -lR

      - name: Docker build
        shell: bash
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT }}
        run: >
          TAG_REG=us.gcr.io/$PROJECT_ID/spinnaker &&
          NEW_VERSION=2.20.x.beta$(date '+%m%d%H%M') &&
          docker build -f Dockerfile.slim -t ${TAG_REG}/front50:${NEW_VERSION} . &&
          docker push ${TAG_REG}/front50:${NEW_VERSION}
